#1D Array slicing operations using NumPy

In [ ]:

import numpy as np

# Creating a 1D array
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# 1. Slice elements from index 2 to 6
print(a[2:7])

# 2. Slice the first 5 elements
print(a[:5])

# 3. Slice all elements except the first and last
print(a[1:-1])

# 4. Slice elements using step size 2
print(a[::2])

# 5. Slice the last 3 elements using negative indexing
print(a[-3:])

# 6. Slice elements from index -6 to -2
print(a[-6:-1])

# 7. Reverse the array using slicing
print(a[::-1])

# 8. Slice elements from index 1 to the second-last element
print(a[1:-1])

# 9. Extract alternate elements starting from the last element
print(a[::-2])

# 10. Slice the array to get [30, 40, 50]
print(a[2:5])

[30 40 50 60 70]
[10 20 30 40 50]
[20 30 40 50 60 70]
[10 30 50 70]
[60 70 80]
[30 40 50 60 70]
[80 70 60 50 40 30 20 10]
[20 30 40 50 60 70]
[80 60 40 20]
[30 40 50]


# 2D Array slicing operations using NumPy

In [ ]:
import numpy as np

# Creating a 2D array
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])

# 1. Extract the second row
print(a[1])

# 2. Extract the third column
print(a[:, 2])

# 3. Extract the sub-matrix [[6,7],[10,11]]
print(a[1:3, 1:3])

# 4. Slice the first two rows and all columns
print(a[:2, :])

# 5. Slice all rows and the last two columns
print(a[:, -2:])

# 6. Extract the last row using negative indexing
print(a[-1])

# 7. Extract the last column using negative indexing
print(a[:, -1])

# 8. Reverse the rows of the array
print(a[::-1])

# 9. Extract the middle 2x2 matrix
print(a[1:3, 1:3])

# 10. Slice rows from index 1 to -1 and columns from 1 to -1
print(a[1:-1, 1:-1])

[5 6 7 8]
[ 3  7 11 15]
[[ 6  7]
 [10 11]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]
[13 14 15 16]
[ 4  8 12 16]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 6  7]
 [10 11]]
[[ 6  7]
 [10 11]]


# 3D Array slicing operations using NumPy

In [ ]:
import numpy as np

# Creating a 3D array
a = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]],

    [[19, 20, 21],
     [22, 23, 24],
     [25, 26, 27]]
])
# 1. Extract the first 2D matrix
print(a[0])

# 2. Extract the second 2D matrix using negative indexing
print(a[-2])

# 3. Extract the element 15 using indexing
print(a[1, 1, 2])

# 4. Extract the first row of the second 2D matrix
print(a[1, 0])

# 5. Extract the last column from all 2D matrices
print(a[:, :, -1])

# 6. Slice the first two 2D matrices completely
print(a[:2])

# 7. Extract the middle layer (matrix) using slicing
print(a[1])

# 8. Extract all elements from rows 1 to -1 and columns 0 to 2 of all layers
print(a[:, 1:-1, 0:3])

# 9. Extract only the diagonal elements of the first 2D matrix
print(a[0].diagonal())

# 10. Reverse the order of 2D matrices in the 3D array
print(a[::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
15
[10 11 12]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[[ 4  5  6]]

 [[13 14 15]]

 [[22 23 24]]]
[1 5 9]
[[[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]]
